### ISSUE TITLE
Theme the rest of sublime

### ISSUE THREAD

**Issue by sammy-ette** [rose-pine/sublime-text#1]
This theme is really nice, but it's only the code part of sublime (color scheme)
I (and other people) would definitely like to have that soho vibes for the entire editor
![](https://modeus.is-inside.me/kU4KeZLw.png)

**Comment by mvllow** [comment]
Completely agree! I was going to start one but got a little overwhelmed with all the options & wanting it to be perfect.

I would actually prefer to use sublime primarily if we had this 😌

**Comment by braver** [comment]
handled in 0392f695d22697610ea66365443b7ca73c6b855a
