### ISSUE TITLE
Deprecated tmTheme file removes support for theming sharkdp/bat 

### ISSUE THREAD

**Issue by arrrgi** [rose-pine/sublime-text#6]
[bat](https://github.com/sharkdp/bat?tab=readme-ov-file#customization) currently uses Sublime Text color theme files to allow for colorization of output.

2552c5a dropped the .tmTheme file ending support for Rosé Pine theme in bat.

Would it be possible to re-add this or would this ideally sit in it's own repo?

**Comment by mvllow** [comment]
I think having a tm-theme repo could be useful. I think that format is used in a few other apps as well. If you wanted to put together the repo I can invite you to the org to transfer it in. Otherwise I'll get to it as soon as I have time :)

**Comment by arrrgi** [comment]
I'm willing to give it a try in a few days time. 

I'll post back here on this issue once I've got a repo ready for review/feedback. I will caveat that I have little time to act as a maintainer going forward, I'm not sure if this is a problem for the project or whether someone else will be able to provide updates/fixes if needed later.

**Comment by mvllow** [comment]
No rush and of course no expectation to maintain it :) Any help is always appreciated!

**Comment by arrrgi** [comment]
@mvllow the new repo is here for you to review and provide feedback on. Feel free to also test with [bat](https://github.com/sharkdp/bat) yourself to confirm this is working for you.

Note: I haven't tested the Dawn theme as I only work on a dark themed terminal as my daily driver. That said, the theme file matches the one created for [Typst](https://github.com/rose-pine/typst) as I used that one for reference.

**Edit:** don't forget to change the URL to `https://raw.githubusercontent.com/arrrgi/tm-theme/main/dist/themes/rose-pine{,-dawn,-moon}.tmTheme` if you use `curl`

**Comment by mvllow** [comment]
Looks great! I invited you to the org if you want to transfer it in. I'll try to add screenshots for the other variants in the future. Thanks for working on this :)

For the about section (within the GitHub sidebar) we should probably change it:

```diff
- Soho vibes for .tmtheme (TextMate compatible) apps
+ Soho vibes for TextMate
# or
+ Soho vibes for .tmtheme apps
```

Or similar, because our site parses out the "Soho vibes for" and the rest will be the name shown on https://rosepinetheme.com/themes/

**Comment by arrrgi** [comment]
> Looks great! I invited you to the org if you want to transfer it in. I'll try to add screenshots for the other variants in the future. Thanks for working on this :)

I've updated the about section and transferred the repo in. Thanks for letting me contribute :)
